## Basic Configuration

baseurl = "https://julionovoa.com"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

author = "Julio Novoa"
title = "Julio Novoa"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-91738952-2"
# enableRobotsTXT = true

## Site Settings
[params]
author = "Julio Novoa"
intro = "Geospatial Data Analytics, Python, R"
description = "Currently working at [LGL Limited](http://lgl.com), British Columbia, Canada"
authorimage = "headshot.jpg"
dateFormat = "2006-JAN-02"

## Site Meta Settings
[params.meta]
description = "Julio Novoa's Website"
keywords = "blog, julionovoa, geospatial, gis, remote sensing, python, rstats"

## Social Accounts
[params.social]
# github = "<username>"
# instagram = "<username>"
linkedin = "julionovoa"
twitter = "JulioPNovoa"
# facebook = "<username>"
# google = "<username>"
# stackoverflow = "<username>"
email = "contact@julionovoa.com"

## Extras
[params.extra]
copyright = "© 2018. Julio Novoa. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = false
highlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
#[[menu.main]]
#    name = "about"
#    identifier = "about"
#    weight = 200
#    url = "/about/"
#[[menu.main]]
#    name = "coderag"
#    identifier = "coderag"
#    weight = 300
#    url = "/coderag/"
